---
version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_PASSWORD=SecurePassHere
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: