apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - "http://*"
                - "https://*"

      k8s_cluster/all_settings:
        auth_type: serviceAccount
        collection_interval: 10s
        node_conditions_to_report: [ "Ready", "MemoryPressure" ]
        allocatable_types_to_report: [ "cpu","memory" ]
        metadata_collection_interval: 20s

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "otelcol"
      debug:
        verbosity: detailed
      otlp:
        endpoint: "3.109.146.170:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlp]
        metrics:
          receivers: [otlp, k8s_cluster/all_settings]
          exporters: [debug, prometheus]
        logs/otlp:
          receivers: [otlp]
          exporters: [debug]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: otel-collector
    name: otel-collector
  name: otel-collector

# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: otel-collector
#   namespace: monitoring
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
  labels:
    app: otel-collector
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - namespaces/status
  - nodes
  - nodes/spec
  - pods
  - pods/status
  - replicationcontrollers
  - replicationcontrollers/status
  - resourcequotas
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - list
    - watch


# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: otel-collector
# rules:
# - apiGroups: [""]
#   resources:
#     - pods
#     - namespaces
#     - nodes
#     - services
#     - endpoints
#     - replicationcontrollers
#     - resourcequotas
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["apps"]
#   resources:
#     - deployments
#     - replicasets
#     - daemonsets
#     - statefulsets
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["batch"]
#   resources:
#     - jobs
#     - cronjobs
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["autoscaling"]
#   resources:
#     - horizontalpodautoscalers
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["extensions"]
#   resources:
#     - replicasets
#   verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
  labels:
    app: otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector
subjects:
- kind: ServiceAccount
  name: otel-collector
  namespace: monitoring

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: otel-collector
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: otel-collector
# subjects:
# - kind: ServiceAccount
#   name: otel-collector
#   namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: prom-metrics
    port: 8889
    protocol: TCP
    targetPort: 8889
  selector:
    app: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        args:
        - "--config=/conf/config.yaml"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 8889
          name: prom-metrics
        volumeMounts:
        - name: config
          mountPath: /conf
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel-collector-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: otel-collector
            port:
              number: 8889
      - path: /v1/traces
        pathType: Prefix
        backend:
          service:
            name: otel-collector
            port:
              number: 4318
      - path: /v1/metrics
        pathType: Prefix
        backend:
          service:
            name: otel-collector
            port:
              number: 4318
      - path: /v1/logs
        pathType: Prefix
        backend:
          service:
            name: otel-collector
            port:
              number: 4318

